services:
  jupyter:
    container_name: quant-dev-jupyter
    build:
      context: ./services/jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks

  kdb:
    container_name: quant-dev-kdb
    build:
      context: ./services/kdb
    ports:
      - "6000:5000"
    tty: true


